import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr] px-4">
        <header className="text-xl font-bold leading-[3rem]">
          Migrado Libre
        </header>
        <main className="py-8">
          {children}
        </main>
        <footer className="text-center leading-[3rem] opacity-70">
          &copy; {new Date().getFullYear()} Dont panic
        </footer>
      </body>
    </html>
  );
}
